# name: "git action"

# on: ["push", "pull_request"]

# jobs:
#   first-job:
#     name: "first job"

#     runs-on: window-latest

#     steps:
#       - name: Say hello world 1
#         shell: bash
#         run: echo "hello world from step 1"

#   second-jobs:
#     name: "second job"
#     if: github.event_name == 'pull_request'

#     runs-on: ubuntu-latest

#     steps:
#       - name: pull request
#         shell: bash
#         run: echo "PULL REQUEST is coming"
